### PR TITLE
Ported the WHOLE game to vitrix engine

### PR DESCRIPTION
**Pull request by Chateauvisionn**

### CODE REVIEW

**Review by ShadityZ — COMMENTED** [review]
Looking okay, just making a few changes with the engine for some finishing touches and bug fixes. Then I'll check out if it works with the new engine

**Comment by Chateauvisionn** [comment]
do i merge?

**Comment by ShadityZ** [comment]
> do i merge?
No, not just yet. I've got a few fixes to the engine I'd like to make before we can merge. Once complete, and thorough testing is done, I will merge it. Its a BIG change, so we need to check for lots of bugs and other issues

**Review by ShadityZ — APPROVED** [review]
I can confirm that this all works for me, I have made my changes and this PR has my stamp of approval!

**Comment by ShadityZ** [comment]
Merging...

**Pull request merged**
