### PR TITLE
Added many things

### PR DESCRIPTION
**Pull request by Chateauvisionn**
Added third person and changed window name, ex: "Vitrix - Singleplayer" and a little anticheat

### CODE REVIEW

**Comment by ShadityZ** [comment]
Wow, didn't think of third person, have you tested it? I might give it a try later

**Comment by Chateauvisionn** [comment]
> Wow, didn't think of third person, have you tested it? I might give it a try later

I tested it but it's not very good, we need a 3d model for the player

**Comment by ShadityZ** [comment]
Maybe modify the PR a little more, then come back to this?

**Comment by Chateauvisionn** [comment]
> Maybe modify the PR a little more, then come back to this? 

Can't someone make a placeholder 3d model ?

**Comment by Chateauvisionn** [comment]
i added the anticheat

**Comment by Chateauvisionn** [comment]
So i made a lot of things, modified anticheat, changed pause system, added inventory, changed README, changed the logo

**Comment by Chateauvisionn** [comment]
I close this, this has bugs and a lot of conflicts i'm gonna make another one

**Pull request closed without merging**
