### PR TITLE
Monthly Pull from Dev Branch - May 2022

### PR DESCRIPTION
**Pull request by ShadityZ**
Most things can be tracked on the project linked to it, found on the right. I know its not May yet, that's why its a draft. Major additions coming, keep up on the MAJOR daily updates!

### CODE REVIEW

**Comment by ShadityZ** [comment]
Alot of things have been going on lately, but soon once the Vitrix Engine PR #53 is merged, and a few more changes are made, this PR will be ready to merge. Expect it to merge around late-May, and releases to come shortly after!

**Comment by ShadityZ** [comment]
Just encountered MAJOR issue #54 that is for multiplayer. Unless that is fixed in time, PR may have to be postponed.

**Comment by ShadityZ** [comment]
Just pushed fix for issue #54, and some new features are coming soon as well. Be on the look out!

**Comment by ShadityZ** [comment]
Mostly completed, just got a few more things, then will merge!

**Comment by ShadityZ** [comment]
Going to perform MAJOR optimizations now, commit coming soon!

**Comment by ShadityZ** [comment]
Just did some clean up for everything! Merging now...

**Comment by davecarrijo** [comment]
That’s a lot of code for one month. Hahaha nicely done guys.

**Pull request merged**
